// Layout configurations for the photobooth
// Supports 1, 2, 3, 4, 5, 6, 8, 9 photos with dynamic arrangements, creative styles, and visual thumbnail geometries.

export const PHOTO_COUNTS = [1, 2, 3, 4, 5, 6, 8, 9];

export const LAYOUTS = [
  // ================= 1 PHOTO =================
  {
    id: '1x1-large',
    photoCount: 1,
    name: 'Single Portrait',
    category: 'Featured',
    description: 'One large beautiful portrait photo',
    stripWidth: 320,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: '0px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '3/4', isFeatured: true },
    ],
    thumbnailSlots: [
      { x: 10, y: 10, w: 80, h: 80, isFeatured: true },
    ],
  },
  {
    id: '1x1-polaroid',
    photoCount: 1,
    name: 'Classic Polaroid',
    category: 'Polaroid',
    description: 'Vintage square instant photo with bottom note margin',
    stripWidth: 300,
    isPolaroid: true,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: '0px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '1/1', isFeatured: true },
    ],
    thumbnailSlots: [
      { x: 15, y: 10, w: 70, h: 70, isFeatured: true },
    ],
  },

  // ================= 2 PHOTOS =================
  {
    id: '2x1-strip',
    photoCount: 2,
    name: 'Vertical Duo Strip',
    category: 'Strip',
    description: 'Classic 2-photo vertical photobooth strip',
    stripWidth: 260,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: '12px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 20, y: 8, w: 60, h: 38 },
      { x: 20, y: 54, w: 60, h: 38 },
    ],
  },
  {
    id: '1x2-side',
    photoCount: 2,
    name: 'Horizontal Duo',
    category: 'Grid',
    description: 'Two side-by-side landscape photos',
    stripWidth: 460,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '12px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 8, y: 20, w: 39, h: 60 },
      { x: 53, y: 20, w: 39, h: 60 },
    ],
  },
  {
    id: '2-polaroid-duo',
    photoCount: 2,
    name: 'Polaroid Duo',
    category: 'Polaroid',
    description: 'Two stacked square polaroid prints',
    stripWidth: 280,
    isPolaroid: true,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: '14px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
    ],
    thumbnailSlots: [
      { x: 22, y: 10, w: 56, h: 36 },
      { x: 22, y: 54, w: 56, h: 36 },
    ],
  },

  // ================= 3 PHOTOS =================
  {
    id: '3x1-strip',
    photoCount: 3,
    name: 'Classic 3-Strip',
    category: 'Strip',
    description: 'Traditional 3-photo vertical photostrip',
    stripWidth: 260,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: '12px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 22, y: 6, w: 56, h: 26 },
      { x: 22, y: 37, w: 56, h: 26 },
      { x: 22, y: 68, w: 56, h: 26 },
    ],
  },
  {
    id: '3-featured-top',
    photoCount: 3,
    name: '1 Large + 2 Small',
    category: 'Featured',
    description: 'Featured hero photo at top with two side-by-side below',
    stripWidth: 380,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '10px',
    },
    slots: [
      { id: 0, colSpan: 2, rowSpan: 1, aspectRatio: '16/10', isFeatured: true },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
    ],
    thumbnailSlots: [
      { x: 10, y: 10, w: 80, h: 42, isFeatured: true },
      { x: 10, y: 58, w: 37, h: 32 },
      { x: 53, y: 58, w: 37, h: 32 },
    ],
  },
  {
    id: '3-featured-bottom',
    photoCount: 3,
    name: '2 Small + 1 Large',
    category: 'Featured',
    description: 'Two side-by-side on top with featured hero banner below',
    stripWidth: 380,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '10px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 2, colSpan: 2, rowSpan: 1, aspectRatio: '16/10', isFeatured: true },
    ],
    thumbnailSlots: [
      { x: 10, y: 10, w: 37, h: 32 },
      { x: 53, y: 10, w: 37, h: 32 },
      { x: 10, y: 48, w: 80, h: 42, isFeatured: true },
    ],
  },

  // ================= 4 PHOTOS =================
  {
    id: '2x2-grid',
    photoCount: 4,
    name: '2×2 Classic Grid',
    category: 'Grid',
    description: 'Clean balanced 2-by-2 square photopack',
    stripWidth: 380,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '10px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
    ],
    thumbnailSlots: [
      { x: 10, y: 10, w: 37, h: 37 },
      { x: 53, y: 10, w: 37, h: 37 },
      { x: 10, y: 53, w: 37, h: 37 },
      { x: 53, y: 53, w: 37, h: 37 },
    ],
  },
  {
    id: '4x1-strip',
    photoCount: 4,
    name: 'Vertical 4-Strip',
    category: 'Strip',
    description: 'Full 4-photo classic vintage vertical strip',
    stripWidth: 260,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: '10px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 24, y: 6, w: 52, h: 19 },
      { x: 24, y: 29, w: 52, h: 19 },
      { x: 24, y: 52, w: 52, h: 19 },
      { x: 24, y: 75, w: 52, h: 19 },
    ],
  },
  {
    id: '4-masonry-hero',
    photoCount: 4,
    name: 'Asymmetric Collage',
    category: 'Collage',
    description: '1 tall featured portrait on left with 3 stacked on right',
    stripWidth: 420,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: '1.2fr 1fr',
      gridTemplateRows: 'repeat(3, 1fr)',
      gap: '8px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 3, aspectRatio: 'auto', isFeatured: true },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 8, y: 8, w: 42, h: 84, isFeatured: true },
      { x: 56, y: 8, w: 36, h: 25 },
      { x: 56, y: 37, w: 36, h: 25 },
      { x: 56, y: 66, w: 36, h: 25 },
    ],
  },
  {
    id: '4-polaroid-grid',
    photoCount: 4,
    name: 'Polaroid 2×2 Set',
    category: 'Polaroid',
    description: 'Four mini polaroid frames in a square collage',
    stripWidth: 380,
    isPolaroid: true,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '12px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
    ],
    thumbnailSlots: [
      { x: 10, y: 10, w: 36, h: 36 },
      { x: 54, y: 10, w: 36, h: 36 },
      { x: 10, y: 54, w: 36, h: 36 },
      { x: 54, y: 54, w: 36, h: 36 },
    ],
  },

  // ================= 5 PHOTOS =================
  {
    id: '5-featured-top',
    photoCount: 5,
    name: '1 Featured Top + 2×2 Grid',
    category: 'Featured',
    description: 'Wide hero banner at top with 2×2 grid below',
    stripWidth: 380,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '10px',
    },
    slots: [
      { id: 0, colSpan: 2, rowSpan: 1, aspectRatio: '16/9', isFeatured: true },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
    ],
    thumbnailSlots: [
      { x: 8, y: 8, w: 84, h: 32, isFeatured: true },
      { x: 8, y: 46, w: 39, h: 24 },
      { x: 53, y: 46, w: 39, h: 24 },
      { x: 8, y: 74, w: 39, h: 24 },
      { x: 53, y: 74, w: 39, h: 24 },
    ],
  },
  {
    id: '5-featured-left',
    photoCount: 5,
    name: '1 Tall Left + 4 Grid',
    category: 'Collage',
    description: 'Tall hero portrait on left with 2×2 block on right',
    stripWidth: 440,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: '1.2fr 1fr 1fr',
      gridTemplateRows: 'repeat(2, 1fr)',
      gap: '8px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 2, aspectRatio: 'auto', isFeatured: true },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
    ],
    thumbnailSlots: [
      { x: 8, y: 8, w: 38, h: 84, isFeatured: true },
      { x: 50, y: 8, w: 20, h: 39 },
      { x: 74, y: 8, w: 20, h: 39 },
      { x: 50, y: 53, w: 20, h: 39 },
      { x: 74, y: 53, w: 20, h: 39 },
    ],
  },
  {
    id: '5x1-strip',
    photoCount: 5,
    name: 'Vertical 5-Strip',
    category: 'Strip',
    description: 'Full 5-photo vertical photobooth keepsake',
    stripWidth: 260,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: '8px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 26, y: 4, w: 48, h: 15 },
      { x: 26, y: 23, w: 48, h: 15 },
      { x: 26, y: 42, w: 48, h: 15 },
      { x: 26, y: 61, w: 48, h: 15 },
      { x: 26, y: 80, w: 48, h: 15 },
    ],
  },

  // ================= 6 PHOTOS =================
  // CRITICAL: 6 photos is strictly 3×2, 2×3, vertical strip, or 1+5 featured layout. NOT 3×3!
  {
    id: '3x2-grid',
    photoCount: 6,
    name: '3×2 Grid (3 rows × 2 cols)',
    category: 'Grid',
    description: 'Balanced portrait grid with 3 rows of 2 photos',
    stripWidth: 380,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '10px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 5, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 10, y: 6, w: 36, h: 26 },
      { x: 54, y: 6, w: 36, h: 26 },
      { x: 10, y: 37, w: 36, h: 26 },
      { x: 54, y: 37, w: 36, h: 26 },
      { x: 10, y: 68, w: 36, h: 26 },
      { x: 54, y: 68, w: 36, h: 26 },
    ],
  },
  {
    id: '2x3-grid',
    photoCount: 6,
    name: '2×3 Grid (2 rows × 3 cols)',
    category: 'Grid',
    description: 'Wide landscape collage with 2 rows of 3 photos',
    stripWidth: 480,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '10px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 5, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 6, y: 15, w: 26, h: 32 },
      { x: 37, y: 15, w: 26, h: 32 },
      { x: 68, y: 15, w: 26, h: 32 },
      { x: 6, y: 53, w: 26, h: 32 },
      { x: 37, y: 53, w: 26, h: 32 },
      { x: 68, y: 53, w: 26, h: 32 },
    ],
  },
  {
    id: '6x1-strip',
    photoCount: 6,
    name: 'Vertical 6-Strip',
    category: 'Strip',
    description: 'Tall classic 6-photo photobooth strip',
    stripWidth: 260,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: '8px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 5, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 26, y: 4, w: 48, h: 12 },
      { x: 26, y: 20, w: 48, h: 12 },
      { x: 26, y: 36, w: 48, h: 12 },
      { x: 26, y: 52, w: 48, h: 12 },
      { x: 26, y: 68, w: 48, h: 12 },
      { x: 26, y: 84, w: 48, h: 12 },
    ],
  },
  {
    id: '6-featured-top',
    photoCount: 6,
    name: '1 Featured + 5 Mosaic',
    category: 'Featured',
    description: 'Large top hero with 2 mid photos and 3 bottom photos',
    stripWidth: 420,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(6, 1fr)',
      gap: '8px',
    },
    slots: [
      { id: 0, colSpan: 6, rowSpan: 1, aspectRatio: '16/9', isFeatured: true },
      { id: 1, colSpan: 3, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 3, rowSpan: 1, aspectRatio: '4/3' },
      { id: 3, colSpan: 2, rowSpan: 1, aspectRatio: '1/1' },
      { id: 4, colSpan: 2, rowSpan: 1, aspectRatio: '1/1' },
      { id: 5, colSpan: 2, rowSpan: 1, aspectRatio: '1/1' },
    ],
    thumbnailSlots: [
      { x: 8, y: 8, w: 84, h: 28, isFeatured: true },
      { x: 8, y: 40, w: 39, h: 24 },
      { x: 53, y: 40, w: 39, h: 24 },
      { x: 8, y: 68, w: 25, h: 24 },
      { x: 37, y: 68, w: 25, h: 24 },
      { x: 67, y: 68, w: 25, h: 24 },
    ],
  },

  // ================= 8 PHOTOS =================
  {
    id: '4x2-grid',
    photoCount: 8,
    name: '4×2 Grid (4 rows × 2 cols)',
    category: 'Grid',
    description: 'Double column photostrip album format',
    stripWidth: 380,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '8px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 5, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 6, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 7, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 10, y: 4, w: 36, h: 19 },
      { x: 54, y: 4, w: 36, h: 19 },
      { x: 10, y: 28, w: 36, h: 19 },
      { x: 54, y: 28, w: 36, h: 19 },
      { x: 10, y: 52, w: 36, h: 19 },
      { x: 54, y: 52, w: 36, h: 19 },
      { x: 10, y: 76, w: 36, h: 19 },
      { x: 54, y: 76, w: 36, h: 19 },
    ],
  },
  {
    id: '2x4-grid',
    photoCount: 8,
    name: '2×4 Grid (2 rows × 4 cols)',
    category: 'Grid',
    description: 'Wide horizontal contact card',
    stripWidth: 560,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(4, 1fr)',
      gap: '8px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 5, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 6, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 7, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 4, y: 15, w: 20, h: 32 },
      { x: 28, y: 15, w: 20, h: 32 },
      { x: 52, y: 15, w: 20, h: 32 },
      { x: 76, y: 15, w: 20, h: 32 },
      { x: 4, y: 53, w: 20, h: 32 },
      { x: 28, y: 53, w: 20, h: 32 },
      { x: 52, y: 53, w: 20, h: 32 },
      { x: 76, y: 53, w: 20, h: 32 },
    ],
  },
  {
    id: '8-contact-sheet',
    photoCount: 8,
    name: 'Contact Sheet 8',
    category: 'Contact',
    description: 'Darkroom film proof style with film numbers',
    stripWidth: 420,
    isFilmstrip: true,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '10px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 5, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 6, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
      { id: 7, colSpan: 1, rowSpan: 1, aspectRatio: '4/3' },
    ],
    thumbnailSlots: [
      { x: 10, y: 4, w: 36, h: 19 },
      { x: 54, y: 4, w: 36, h: 19 },
      { x: 10, y: 28, w: 36, h: 19 },
      { x: 54, y: 28, w: 36, h: 19 },
      { x: 10, y: 52, w: 36, h: 19 },
      { x: 54, y: 52, w: 36, h: 19 },
      { x: 10, y: 76, w: 36, h: 19 },
      { x: 54, y: 76, w: 36, h: 19 },
    ],
  },

  // ================= 9 PHOTOS =================
  // CRITICAL: 3×3 Grid is strictly for 9 photos!
  {
    id: '3x3-grid',
    photoCount: 9,
    name: '3×3 Mosaic Grid',
    category: 'Grid',
    description: 'Classic 9-photo 3×3 square mosaic wall',
    stripWidth: 440,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '8px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 5, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 6, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 7, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 8, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
    ],
    thumbnailSlots: [
      { x: 6, y: 6, w: 26, h: 26 },
      { x: 37, y: 6, w: 26, h: 26 },
      { x: 68, y: 6, w: 26, h: 26 },
      { x: 6, y: 37, w: 26, h: 26 },
      { x: 37, y: 37, w: 26, h: 26 },
      { x: 68, y: 37, w: 26, h: 26 },
      { x: 6, y: 68, w: 26, h: 26 },
      { x: 37, y: 68, w: 26, h: 26 },
      { x: 68, y: 68, w: 26, h: 26 },
    ],
  },
  {
    id: '9-featured-center',
    photoCount: 9,
    name: 'Center Hero + 8 Border',
    category: 'Featured',
    description: '3×3 layout with a featured center frame',
    stripWidth: 440,
    containerStyle: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '8px',
    },
    slots: [
      { id: 0, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 1, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 2, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 3, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 4, colSpan: 1, rowSpan: 1, aspectRatio: '1/1', isFeatured: true },
      { id: 5, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 6, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 7, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
      { id: 8, colSpan: 1, rowSpan: 1, aspectRatio: '1/1' },
    ],
    thumbnailSlots: [
      { x: 6, y: 6, w: 26, h: 26 },
      { x: 37, y: 6, w: 26, h: 26 },
      { x: 68, y: 6, w: 26, h: 26 },
      { x: 6, y: 37, w: 26, h: 26 },
      { x: 37, y: 37, w: 26, h: 26, isFeatured: true },
      { x: 68, y: 37, w: 26, h: 26 },
      { x: 6, y: 68, w: 26, h: 26 },
      { x: 37, y: 68, w: 26, h: 26 },
      { x: 68, y: 68, w: 26, h: 26 },
    ],
  },
];

export const getLayoutsForCount = (count) => {
  return LAYOUTS.filter((layout) => layout.photoCount === count);
};

export const getDefaultLayoutForCount = (count) => {
  const matching = getLayoutsForCount(count);
  return matching[0] || LAYOUTS[0];
};

export const COLOR_PRESETS = [
  { label: 'Paper Cream', value: '#FFF7EF', textDark: true },
  { label: 'Studio White', value: '#FFFFFF', textDark: true },
  { label: 'Midnight Black', value: '#18181B', textDark: false },
  { label: 'Curtain Red', value: '#C4234B', textDark: false },
  { label: 'Velvet Plum', value: '#4A1525', textDark: false },
  { label: 'Bubblegum Pink', value: '#FFB5D0', textDark: true },
  { label: 'Vintage Butter', value: '#FDE047', textDark: true },
  { label: 'Matcha Green', value: '#A7F3D0', textDark: true },
  { label: 'Retro Sky', value: '#BAE6FD', textDark: true },
  { label: 'Lavender Dream', value: '#E9D5FF', textDark: true },
];

export const STICKER_SETS = [
  {
    id: 'aot',
    name: 'Attack on Titan',
    stickers: [
      { id: 'mikasa', src: '/stickers/mikasa-bg.png', name: 'Mikasa' },
      { id: 'eren', src: '/stickers/eren-bg.png', name: 'Eren' },
      { id: 'levi', src: '/stickers/levi-bg.png', name: 'Levi' },
      { id: 'annie', src: '/stickers/annie-bg.png', name: 'Annie' },
    ],
  },
  {
    id: 'none',
    name: 'Clean (No Stickers)',
    stickers: [],
  },
];
